# Workflow name:
name: "publish `master` branch."

# Special permissions for `secrets.GITHUB_TOKEN`:
permissions:
  contents: write
  packages: write

# Run on:
on:
  # Demand:
  workflow_dispatch:

# Jobs:
jobs:
  # ---- . ---- ---- ---- ---- . ----
  # Main:
  # ---- . ---- ---- ---- ---- . ----
  main:
    name: "publish `master` branch."
    runs-on: ubuntu-latest

    steps:
      # ---- . ---- ---- ---- ---- . ----
      # CHECKOUT:
      # ---- . ---- ---- ---- ---- . ----

      - name: "CHECKOUT: `${{ github.repository }}`"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          fetch-depth: 0
          submodules: recursive

      # ---- . ---- ---- ---- ---- . ----
      # NODE:
      # ---- . ---- ---- ---- ---- . ----

      - name: "NODE: setup node"
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: "NODE: install dependencies"
        run: npm ci && npm dedupe

      # ---- . ---- ---- ---- ---- . ----
      # VERSION:
      # ---- . ---- ---- ---- ---- . ----

      - name: "VERSION: get version from package.json"
        id: PACKAGE_VERSION
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: "."

      - name: "VERSION: print version"
        run: echo "$PACKAGE_VER"
        env:
          PACKAGE_VER: v${{ steps.PACKAGE_VERSION.outputs.current-version }}

      # ---- . ---- ---- ---- ---- . ----
      # PUBLISH:
      # ---- . ---- ---- ---- ---- . ----

      # Ensure master branch is active:
      - name: "PUBLISH: git checkout master"
        run: git checkout master

      # Test before publishing:
      - name: "PUBLISH: npm run test"
        run: npm run test

      # NPM login via ~/.npmrc:
      - name: "PUBLISH: echo 'token' > ~/.npmrc"
        run: |
          echo 'registry=https://registry.npmjs.org/' > ~/.npmrc
          echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' >> ~/.npmrc
          echo '//registry.npmjs.org/:always-auth=true' >> ~/.npmrc

      # NPM publish:
      - name: "PUBLISH: npm publish"
        run: npm publish --scope="@patryk-b" --registry="https://registry.npmjs.org" --access="public"

      # ---- . ---- ---- ---- ---- . ----
      # TAG:
      # ---- . ---- ---- ---- ---- . ----

      # Create new tag:
      - name: "TAG: git tag"
        run: git tag "v${{ steps.PACKAGE_VERSION.outputs.current-version }}"

      # Push tag:
      - name: "TAG: git push origin --tags"
        run: git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git --tags

      # ---- . ---- ---- ---- ---- . ----
      # RELEASE:
      # ---- . ---- ---- ---- ---- . ----

      - name: "RELEASE: create github release"
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          name: "v${{ steps.PACKAGE_VERSION.outputs.current-version }}"
          tag_name: "latest"
          make_latest: true
