# Workflow name:
name: "rebase `master` branch."

# Special permissions for `secrets.GITHUB_TOKEN`:
permissions:
  contents: write

# Run on:
on:
  # Demand:
  workflow_dispatch:

# Variables:
env:
  SOURCE_BRANCH: dev
  TARGET_BRANCH: master

# Jobs:
jobs:
  # ---- . ---- ---- ---- ---- . ----
  # Main:
  # ---- . ---- ---- ---- ---- . ----
  main:
    name: "rebase `master` branch."
    runs-on: ubuntu-latest

    steps:
      # ---- . ---- ---- ---- ---- . ----
      # CHECKOUT:
      # ---- . ---- ---- ---- ---- . ----

      - name: "CHECKOUT: `${{ github.repository }}`"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          fetch-depth: 0
          submodules: recursive

      # ---- . ---- ---- ---- ---- . ----
      # NODE:
      # ---- . ---- ---- ---- ---- . ----

      - name: "NODE: setup node"
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: "NODE: install dependencies"
        run: npm ci && npm dedupe

      # ---- . ---- ---- ---- ---- . ----
      # REBASE:
      # ---- . ---- ---- ---- ---- . ----

      - name: "REBASE: git fetch --all"
        run: git fetch --all

      # ensure <target> branch is fetched:
      - name: "REBASE: git checkout master"
        run: git checkout $TARGET_BRANCH

      # ensure <source> branch is fetched:
      - name: "REBASE: git checkout dev"
        run: git checkout $SOURCE_BRANCH

      # rebase <source> <target>:
      - name: "REBASE: git rebase dev master"
        run: git rebase $SOURCE_BRANCH $TARGET_BRANCH

      # ensure <target> branch is active:
      - name: "REBASE: git checkout master"
        run: git checkout $TARGET_BRANCH

      # run test before pushing to origin/<target>:
      - name: "REBASE: run test"
        run: npm run test

      # push changes:
      - name: "REBASE: git push origin master"
        run: git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git $TARGET_BRANCH
